# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3c4b851904cc42d642f303a662d54ff4"
name = "insane-product-reservation"
handle = "insane-product-reservation"
application_url = "https://insane-product-reservation.onrender.com/"
embedded = true

[build]
dev_store_url = "insane-reservation-system.myshopify.com"
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_customers,read_customers,write_orders,read_orders,unauthenticated_read_product_listings,unauthenticated_read_product_tags,unauthenticated_read_checkouts"

[auth]
redirect_urls = [ "https://insane-product-reservation.onrender.com/api/auth" ]

[pos]
embedded = false